#!/bin/bash
echo Build the cookbook
composer install
pear channel-discover pear.phing.info
pear install phing/phing
phpenv rehash
phing setupTest
composer dump-autoload
phing buildDeploy
cp -r conf/envs/prod/openshift/config .
cp -r build/www .