#!/bin/bash

if [ ! -f "$OPENSHIFT_PHP_DIR/usr/bin/phing" ]; then
    echo Installing phing
    cd $OPENSHIFT_DATA_DIR
    wget http://www.phing.info/get/phing-2.16.0.phar -O phing.phar --quiet
    chmod +x phing.phar
    cd $OPENSHIFT_PHP_DIR/usr/bin
    mv $OPENSHIFT_DATA_DIR/phing.phar phing
fi


if [ ! -f "$OPENSHIFT_PHP_DIR/usr/bin/phpdoc" ]; then
    echo Installing phpDocumentor
    cd $OPENSHIFT_DATA_DIR
    wget https://github.com/phpDocumentor/phpDocumentor2/releases/download/v2.9.0/phpDocumentor.phar --quiet
    chmod +x phpDocumentor.phar
    cd $OPENSHIFT_PHP_DIR/usr/bin
    mv $OPENSHIFT_DATA_DIR/phpDocumentor.phar phpdoc
fi

echo Prepare the cookbook directory
mv $OPENSHIFT_REPO_DIR/conf/envs/prod/openshift/config $OPENSHIFT_REPO_DIR/config
mkdir $OPENSHIFT_REPO_DIR/www
mv $OPENSHIFT_REPO_DIR/conf $OPENSHIFT_REPO_DIR/www/conf
mv $OPENSHIFT_REPO_DIR/cookbook $OPENSHIFT_REPO_DIR/www/cookbook
mv $OPENSHIFT_REPO_DIR/generated-migrations $OPENSHIFT_REPO_DIR/www/generated-migrations
mv $OPENSHIFT_REPO_DIR/*.* $OPENSHIFT_REPO_DIR/www
cp $OPENSHIFT_DATA_DIR/propel.yml $OPENSHIFT_REPO_DIR/www/conf/envs/prod/propel.yml

echo Retrieving dependencies with composer...
cd $OPENSHIFT_REPO_DIR/www ; 
composer self-update
composer install --no-dev

echo build cookbook
phing setupProd
composer dump-autoload

phing docs