language: php

php:
- '5.6'
- '7.0'
- '7.1'

services:
- mysql

before_script:
- mysql -u root -e "CREATE DATABASE IF NOT EXISTS cookbooktest;"
- mysql -u root -e "CREATE USER 'devuser'@'localhost' IDENTIFIED BY 'devpass';"
- mysql -u root -e "GRANT ALL ON cookbooktest.* TO 'devuser'@'localhost';"
- composer install
- pear channel-discover pear.phing.info
- pear install phing/phing
- phpenv rehash
- phing setupTest
- composer dump-autoload

script: phing test

deploy:
  provider: openshift
  user: sandrine.beauche@gmail.com
  password:
    secure: A1e96DdXED75dZxrg4DouuVHCSAJ8AIirFQtfjKqcBw8V0cNYMhwH8y1XmC+w1JEWIelBt8PZbRojAhNwdqdXBr0vE1xxq8pzlRfxFV0b2BJNiEahe5UDdzJcj4rfs6V3Frq0woJf6gWutfroaqSS2RoknZDkuGo30xPhLkdqbpkruyEGZq0fFhfVg/toVQ8dn+2KVsAJScYABB8sGDZg2Ec5os1ebFpZVbpbq0gMV6GhhoRXZxVLYEG4gh5Wq72kInyd6QRdEdCqyGpanGWk6LiYIjSmq6aj5Je5vsjd5mZHrMq94nmt3n5psbNa9N3TrDcRn96aqRUuvi8dl8Q94qLZ/pYlfKoG5T2jwankX5ydWKlRpXogVzX6ScOiWZwXafn+SaaOFAK3HM3iirsupMOL/52F2S0lYX20ravQEeaPoBzKbl/Cc3Y3q3Ng3ZzKbMiP7rTfp/lJ+DF8v/81Xb7ghin4umoFmjImovdTGaEUwLVSLI/zj7glK84xh5XaHmFybCeUHh9ruXHf6IvL+RLC+AdtnnFLGbLy36njIJwyupEmu8FPBRSgwYw62jSf6H9+q1sR6+1ZldVmMLCEireUT+m3Wjcen7Qv3yrNPrGrIDyhCg46gLd+a7pKbi4jflBGwJn/+dNJzRZIaoOayeELMszF1tHpbPG7e+MYv4=
  app: cookbook
  domain: chezsandrine
  skip_cleanup: true
  on:
    repo: sandrineBeauche/cookbookServer2
    php: 7.0
    
