## YAML Template.
language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  
services:
  - mysql
  
before_script:
  - mysql -u root -e "CREATE DATABASE IF NOT EXISTS cookbooktest;"
  - mysql -u root -e "CREATE USER IF NOT EXISTS 'devuser'@'localhost' IDENTIFIED BY 'devpass';"
  - mysql -u root -e "GRANT ALL ON cookbooktest.* TO 'devuser'@'localhost';"
