language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  
services:
  - mysql
  
before_script:
    # Prepare the connection to the test database
  - mysql -u root -e "CREATE DATABASE IF NOT EXISTS cookbooktest;"
  - mysql -u root -e "CREATE USER 'devuser'@'localhost' IDENTIFIED BY 'devpass';"
  - mysql -u root -e "GRANT ALL ON cookbooktest.* TO 'devuser'@'localhost';"
    # download and install all the PHP dependencies
  - composer install
    # install phing build tool
  - pear channel-discover pear.phing.info
  - pear install phing/phing
  - phpenv rehash
    # build the project with phing
  - phing setupTest

script: phing test
  

